export const featuredDestinations = [
  {
    id: "1",
    name: "Santorini",
    country: "Greece",
    image: "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=500&h=600&fit=crop",
    rating: 4.9,
    reviews: 2847,
    price: 180,
    description: "Stunning sunsets and white-washed buildings overlooking the Aegean Sea",
    travelers: 15420,
  },
  {
    id: "2",
    name: "Bali",
    country: "Indonesia",
    image: "https://images.unsplash.com/photo-1537953773345-d172ccf13cf1?w=500&h=600&fit=crop",
    rating: 4.8,
    reviews: 3921,
    price: 95,
    description: "Tropical paradise with ancient temples, lush rice terraces, and pristine beaches",
    travelers: 28750,
  },
  {
    id: "3",
    name: "Kyoto",
    country: "Japan",
    image: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=500&h=600&fit=crop",
    rating: 4.95,
    reviews: 1876,
    price: 220,
    description: "Historic temples, traditional gardens, and authentic Japanese culture",
    travelers: 12340,
  },
  {
    id: "4",
    name: "Maldives",
    country: "Maldives",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=500&h=600&fit=crop",
    rating: 4.92,
    reviews: 1543,
    price: 450,
    description: "Crystal clear waters, overwater bungalows, and pristine coral reefs",
    travelers: 8920,
  },
  {
    id: "5",
    name: "Tuscany",
    country: "Italy",
    image: "https://images.unsplash.com/photo-1523906834658-6e24ef2386f9?w=500&h=600&fit=crop",
    rating: 4.87,
    reviews: 2156,
    price: 160,
    description: "Rolling hills, vineyards, and charming medieval towns",
    travelers: 18650,
  },
  {
    id: "6",
    name: "Banff",
    country: "Canada",
    image: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=500&h=600&fit=crop",
    rating: 4.91,
    reviews: 1789,
    price: 140,
    description: "Majestic mountains, pristine lakes, and abundant wildlife",
    travelers: 14230,
  },
  {
    id: "7",
    name: "Marrakech",
    country: "Morocco",
    image: "https://images.unsplash.com/photo-1539650116574-75c0c6d73f6e?w=500&h=600&fit=crop",
    rating: 4.76,
    reviews: 2934,
    price: 85,
    description: "Vibrant souks, stunning architecture, and rich cultural heritage",
    travelers: 21450,
  },
  {
    id: "8",
    name: "Patagonia",
    country: "Chile",
    image: "https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=500&h=600&fit=crop",
    rating: 4.89,
    reviews: 987,
    price: 200,
    description: "Dramatic landscapes, glaciers, and untouched wilderness",
    travelers: 6780,
  },
]

export const categories = [
  {
    id: "1",
    name: "Beachfront",
    icon: "🏖️",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=300&fit=crop",
  },
  {
    id: "2",
    name: "Mountains",
    icon: "🏔️",
    image: "https://images.unsplash.com/photo-1464822759844-d150baec0494?w=400&h=300&fit=crop",
  },
  {
    id: "3",
    name: "City",
    icon: "🏙️",
    image: "https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=400&h=300&fit=crop",
  },
  {
    id: "4",
    name: "Countryside",
    icon: "🌾",
    image: "https://images.unsplash.com/photo-1464822759844-d150baec0494?w=400&h=300&fit=crop",
  },
  {
    id: "5",
    name: "Desert",
    icon: "🏜️",
    image: "https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?w=400&h=300&fit=crop",
  },
  {
    id: "6",
    name: "Islands",
    icon: "🏝️",
    image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=400&h=300&fit=crop",
  },
  {
    id: "7",
    name: "Forest",
    icon: "🌲",
    image: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=400&h=300&fit=crop",
  },
  {
    id: "8",
    name: "Lake",
    icon: "🏞️",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=300&fit=crop",
  },
  {
    id: "9",
    name: "Ski",
    icon: "⛷️",
    image: "https://images.unsplash.com/photo-1551524164-6cf2ac8d0bf9?w=400&h=300&fit=crop",
  },
  {
    id: "10",
    name: "Tropical",
    icon: "🌴",
    image: "https://images.unsplash.com/photo-1537953773345-d172ccf13cf1?w=400&h=300&fit=crop",
  },
  {
    id: "11",
    name: "Historic",
    icon: "🏛️",
    image: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=400&h=300&fit=crop",
  },
  {
    id: "12",
    name: "Unique",
    icon: "✨",
    image: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=400&h=300&fit=crop",
  },
]

export const inspirationCategories = [
  {
    title: "Popular destinations",
    items: [
      { name: "Canmore", location: "Pet-friendly rentals" },
      { name: "Benalmádena", location: "Beach house rentals" },
      { name: "Marbella", location: "Villa rentals" },
      { name: "Mijas", location: "House rentals" },
      { name: "Prescott", location: "Cabin rentals" },
      { name: "Scottsdale", location: "Mansion rentals" },
      { name: "Tucson", location: "House rentals" },
      { name: "Jasper", location: "Cabin rentals" },
      { name: "Mountain View", location: "Family-friendly rentals" },
      { name: "Devonport", location: "Cottage rentals" },
      { name: "Mallacoota", location: "Pet-friendly rentals" },
      { name: "Ibiza", location: "Vacation rentals" },
    ],
  },
  {
    title: "Arts & culture",
    items: [
      { name: "Phoenix", location: "Vacation rentals" },
      { name: "Hot Springs", location: "Cabin rentals" },
      { name: "Los Angeles", location: "Apartment rentals" },
      { name: "San Diego", location: "Beach house rentals" },
      { name: "San Francisco", location: "Vacation rentals" },
      { name: "Barcelona", location: "Apartment rentals" },
      { name: "Prague", location: "Vacation rentals" },
      { name: "Washington", location: "Vacation rentals" },
      { name: "Keswick", location: "Cottage rentals" },
      { name: "London", location: "Vacation rentals" },
      { name: "Scarborough", location: "Beach house rentals" },
      { name: "Sherwood Forest", location: "Cabin rentals" },
    ],
  },
  {
    title: "Outdoors",
    items: [
      { name: "Lake Martin", location: "Vacation rentals" },
      { name: "Banff", location: "Vacation rentals" },
      { name: "Nerja", location: "Beach house rentals" },
      { name: "Greer", location: "Cabin rentals" },
      { name: "Lake Havasu City", location: "House rentals" },
      { name: "Lake Powell", location: "House rentals" },
      { name: "North Rim", location: "Vacation rentals" },
      { name: "Payson", location: "Vacation rentals" },
      { name: "Pinetop-Lakeside", location: "Cabin rentals" },
      { name: "Red Rock", location: "Cabin rentals" },
      { name: "Dinner Plain", location: "Vacation rentals" },
      { name: "Streaky Bay", location: "Vacation rentals" },
    ],
  },
  {
    title: "Mountains",
    items: [
      { name: "Mentone", location: "Cabin rentals" },
      { name: "Sedona", location: "Vacation rentals" },
      { name: "Helen", location: "Cabin rentals" },
      { name: "Pine Mountain", location: "Vacation rentals" },
      { name: "Stone Mountain", location: "Cabin rentals" },
      { name: "Island Park", location: "Cabin rentals" },
      { name: "Blue Mountains", location: "Vacation rentals" },
      { name: "Asheville", location: "Vacation rentals" },
      { name: "Blowing Rock", location: "Vacation rentals" },
      { name: "Boone", location: "Vacation rentals" },
      { name: "Hochatown", location: "Vacation rentals" },
      { name: "Pigeon Forge", location: "Vacation rentals" },
    ],
  },
  {
    title: "Beach",
    items: [
      { name: "Dauphin Island", location: "Beach house rentals" },
      { name: "Fort Morgan", location: "Beach house rentals" },
      { name: "Gulf Shores", location: "Beach house rentals" },
      { name: "Huntington Beach", location: "Beach house rentals" },
      { name: "Newport Beach", location: "Vacation rentals" },
      { name: "Big Sur", location: "Vacation rentals" },
      { name: "Bodega Bay", location: "Vacation rentals" },
      { name: "Cambria", location: "Beach house rentals" },
      { name: "Cayucos", location: "Beach house rentals" },
      { name: "Huntington Beach", location: "Vacation rentals" },
      { name: "Long Beach", location: "Vacation rentals" },
      { name: "Morro Bay", location: "Beach house rentals" },
    ],
  },
  {
    title: "Unique stays",
    items: [
      { name: "Cabins", location: "United States" },
      { name: "Treehouses", location: "United States" },
      { name: "Glamping", location: "United States" },
      { name: "Tiny houses", location: "United States" },
      { name: "Beach houses", location: "United States" },
      { name: "Campers and RVs", location: "United States" },
      { name: "Lakefront", location: "United States" },
      { name: "Ski-in/Ski-out", location: "United States" },
      { name: "Castle", location: "United States" },
      { name: "Houseboat", location: "United States" },
      { name: "Farm stays", location: "United States" },
      { name: "Luxury rentals", location: "United States" },
    ],
  },
]

export const propertyTypes = [
  {
    id: "1",
    name: "Luxury Villas",
    icon: "🏖️",
    image: "https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=400&h=300&fit=crop",
    count: 1250,
  },
  {
    id: "2",
    name: "Mountain Cabins",
    icon: "🏔️",
    image: "https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=400&h=300&fit=crop",
    count: 890,
  },
  {
    id: "3",
    name: "City Apartments",
    icon: "🏙️",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=400&h=300&fit=crop",
    count: 2340,
  },
  {
    id: "4",
    name: "Beach Houses",
    icon: "🌊",
    image: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=400&h=300&fit=crop",
    count: 1680,
  },
  {
    id: "5",
    name: "Countryside Retreats",
    icon: "🌾",
    image: "https://images.unsplash.com/photo-1464822759844-d150baec0494?w=400&h=300&fit=crop",
    count: 750,
  },
  {
    id: "6",
    name: "Unique Stays",
    icon: "✨",
    image: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=400&h=300&fit=crop",
    count: 420,
  },
]

export const experiences = [
  {
    id: "1",
    title: "Cooking Classes",
    description: "Learn local cuisine from expert chefs",
    image: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=300&fit=crop",
    price: 75,
    duration: "3 hours",
    rating: 4.8,
  },
  {
    id: "2",
    title: "Adventure Tours",
    description: "Thrilling outdoor activities and exploration",
    image: "https://images.unsplash.com/photo-1551632811-561732d1e306?w=400&h=300&fit=crop",
    price: 120,
    duration: "Full day",
    rating: 4.9,
  },
  {
    id: "3",
    title: "Cultural Walks",
    description: "Discover hidden gems with local guides",
    image: "https://images.unsplash.com/photo-1539650116574-75c0c6d73f6e?w=400&h=300&fit=crop",
    price: 45,
    duration: "2 hours",
    rating: 4.7,
  },
  {
    id: "4",
    title: "Art Workshops",
    description: "Create beautiful art with local artists",
    image: "https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=400&h=300&fit=crop",
    price: 90,
    duration: "4 hours",
    rating: 4.85,
  },
]

export const travelCategories = [
  {
    title: "Popular Destinations",
    items: [
      {
        name: "Paris",
        location: "France",
        image: "https://images.unsplash.com/photo-1502602898536-47ad22581b52?w=300&h=200&fit=crop",
      },
      {
        name: "Tokyo",
        location: "Japan",
        image: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=300&h=200&fit=crop",
      },
      {
        name: "New York",
        location: "USA",
        image: "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=300&h=200&fit=crop",
      },
      {
        name: "London",
        location: "UK",
        image: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=300&h=200&fit=crop",
      },
    ],
  },
  {
    title: "Unique Experiences",
    items: [
      {
        name: "Northern Lights",
        location: "Iceland",
        image: "https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=300&h=200&fit=crop",
      },
      {
        name: "Safari Adventure",
        location: "Kenya",
        image: "https://images.unsplash.com/photo-1516426122078-c23e76319801?w=300&h=200&fit=crop",
      },
      {
        name: "Desert Camping",
        location: "Morocco",
        image: "https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?w=300&h=200&fit=crop",
      },
      {
        name: "Island Hopping",
        location: "Greece",
        image: "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=300&h=200&fit=crop",
      },
    ],
  },
  {
    title: "Adventure Activities",
    items: [
      {
        name: "Mountain Climbing",
        location: "Nepal",
        image: "https://images.unsplash.com/photo-1464822759844-d150baec0494?w=300&h=200&fit=crop",
      },
      {
        name: "Scuba Diving",
        location: "Maldives",
        image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=300&h=200&fit=crop",
      },
      {
        name: "Skydiving",
        location: "New Zealand",
        image: "https://images.unsplash.com/photo-1540979388789-6cee28a1cdc9?w=300&h=200&fit=crop",
      },
      {
        name: "Surfing",
        location: "Hawaii",
        image: "https://images.unsplash.com/photo-1502680390469-be75c86b636f?w=300&h=200&fit=crop",
      },
    ],
  },
]
